services:
  nasa-rover-pics-backend:
    build:
      context: .
      dockerfile: DockerFile
      target: base
    volumes:
      - ./src:/usr/src/app/src
      - ./nodemon.json:/usr/src/app/nodemon.json
    container_name: nasa-rover-pics-backend
    expose:
      - '1337'
    ports:
      - '1337:1337'
    command: npm run serve
